FROM node:20 AS development

# Set environment variable for development
ARG NODE_ENV=development

ENV NODE_ENV=$NODE_ENV

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

RUN npm install --prefer-offline --no-audit --progress=false

# Configure permissions for the 'node' user
RUN chown -R node:node .

# Change to the 'node' user to avoid running as root
USER node

# Expose port
EXPOSE 3000

# Start application in development mode
CMD ["npm", "run", "start:dev"]
